apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-elgholmy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-elgholmy
  template:
    metadata:
      labels:
        app: hello-elgholmy
    spec:
      containers:
      - name: hello-elgholmy
        image: abdullahsaleh2001/hello-elgholmy:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"