apiVersion: v1
kind: Service
metadata:
  name: hello-elgholmy
spec:
  selector:
    app: hello-elgholmy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Choose a port in the range 30000-32767
  type: NodePort
