apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  selector:
    app: greeting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Choose a port between 30000-32767
  type: NodePort  # Exposes the service on a static port
