apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-devops-app
  template:
    metadata:
      labels:
        app: hello-devops-app
    spec:
      containers:
        - name: hello-devops-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          env:
            - name: MESSAGE
              value: "Hello Abdallah, Our new DevOps at Inspire"
