apiVersion: v1
kind: Service
metadata:
  name: hello-devops-service
  namespace: default
spec:
  selector:
    app: hello-devops-app
  ports:
    - protocol: TCP
      port: 9000       # The service port
      targetPort: 80   # The container port
      nodePort: 32000  # Choose a port in the 30000-32767 range
  type: NodePort
