apiVersion: v1
kind: Service
metadata:
  name: hello-devops-service
  namespace: default
spec:
  selector:
    app: hello-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
