apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080 # Optional: specify a port number (should be within the NodePort range 30000-32767)
  type: NodePort
